### ISSUE TITLE
Week 4 Discussion

### ISSUE THREAD

**Issue by kayvee** [stefanbund/cis155#11]
Topic has been posted!
http://seaport.coastline.edu/Ext/Courses/Browse/Announcement.cfm?AnnouncementID=58683

*_What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering? *_

**Comment by kayvee** [comment]
_**What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering?_*

I haven't experienced any major struggles or questions since last time because I finished all the videos and submitted it all together for Milestone 1. I am just waiting for feedback before I continue. One thing I'll need to do is research Hashes and ArrayLists in Java more so I can use them for my random output for the Stock class. Except for this, nothing is causing any errors or bugs. I'll need to still follow my plan of fixing all the code with comments and a flow of logic to review, while watching the videos again, but I'm happy with my progress thus far and I'm just waiting for Milestone 2 to be posted :)

Good luck everyone!

**Comment by stefanbund** [comment]
This was posted today, but folks were notified via email

From Stefan

**Comment by stefanbund** [comment]
You can rely upon array lists for all large collection situations. This is what I demo in the Videos. We will likely use hashes toward the third project, which will require large sets, compressed uniquely.

As for the milestone, I simply want to see what you have thus far, and will give you credit for the last two weeks of work. I have also posted feedback on the first milestone. Thanks again, stefan

From Stefan

**Comment by kayvee** [comment]
@stefanbund - sorry, I'm not sure why I didn't get the emails!

And perfect. Glad to hear it! Are videos 9-16 what we are expected to have completed by the end of the week, then? Videos 17+ seem to be about Phase 2.

**Comment by forrestbennett** [comment]
One bug that I am experiencing is the inability to create a method because of the absence of syntax coloring. I can't recall why a word might get coloring so I am unable to rectify the problem. Anyone know why I wouldn't be getting syntax coloring where I should? Any help would be greatly appreciated. 

![screen shot 2016-02-28 at 5 53 47 am](https://cloud.githubusercontent.com/assets/17039846/13379650/60fd9494-dde0-11e5-841b-0ddacc7c5e0f.jpg)

**Comment by Irfan009** [comment]
*_What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering?_

Hi Guys,
    I have watched 16 of the videos posted on the YouTube channel and have completed the work shown in those videos too. I have not had any issues while watching the videos and repeating the same thing. i was also able to get the same out put as shown in the lessons but considering the size of the project and Varity of different functions learned at times I feel lost and again, in my opinion this can & only be fixed by practice and repetitions.  
So, I am going to watch all the video again, create many small, simple projects that will be different from what we are working on and start from building/using/experimenting with constructor, loops, arrays etc. I am sure this will help understand & remember the stuff better. 
If any one has other ideas/questions please advice ☺
~ Irfan

**Comment by stefanbund** [comment]
The project does require some structural dependencies. In other words, you need to create some small things that add up to the total structure. It is partially an exercise in engineering something larger, by creating a collection of small classes, each with their own purpose. When working  structurally in this way, the smaller programs you build add up to something more meaningful.

From Stefan

**Comment by pricedjp** [comment]
*What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering? *

I have worked through the videos but still don't feel like I have a solid grasp of the language, although I do feel more comfortable as I am practicing coding more frequently. Understanding how all the classes, methods, arrays, loops, and constructors (the big 5 you referenced in your videos) all work together to help you program has been hard but I am going to keep practicing and hopefully I'll have a solid grasp of the language by the end of the course.

**Comment by forrestbennett** [comment]
@pricedjp Im with you. It is a new language but with repetition it will become clear. I posted an issue yesterday, anyone have any ideas??

**Comment by stefanbund** [comment]
I think your point is very valid. I am putting you through a basic language Boot Camp, where you will see 95% of the core java language after the first four weeks. This means that you will get a rapid overview of what programming is about, and the tools needed to produce it. There won't be specific mastery over any piece of the language, at this time. Rather, a big picture map of how to make a program. 

Students will be experiencing arrays, loops, variables and conditional statements. Then they will incorporate those tools into methods and classes. This is the vast majority of the programming tool set, and knowing these tools, it liberates you to solve many, many problems.

From Stefan

**Comment by stefanbund** [comment]
Just looking at your code, there doesn't appear to be any errors. You would get syntax coloring where you used a variable incorrectly, misspelled something, etc.…

From Stefan

**Comment by pricedjp** [comment]
had a general question for @stefanbund @forrestbennett @kayvee or anyone else: do you find that you learn or have learnt programming best by (1) following videos (like those in this class) and practicing; or (2) following from a textbook (or another online/outside source) and practicing? Both? I feel like I am learning best by just doing. But maybe I am going about it wrong?

**Comment by calvinln** [comment]
What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering?
I feel I need more practice so I'm more comfortable with the language. I forget the syntax occasionally and need to refer to the video. I also have a hard time remembering the names of new methods and which import I should use if I want to use them, but I was able to solve these kinds of problems by watching the videos again. There are a number of classes and sometimes I get lost keeping track of what they should be doing and their responsibilities. I guess it takes time to get comfortable with the language.
Calvin

**Comment by WesleyTo** [comment]
**_What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering?_**

I didn't have much trouble with the project itself. I'm going ahead and trying to do everything programmatically without any hardcoded stuff, and the complexity grew quite quickly, but it's nothing I couldn't handle. I've got it executing for 100000 buyers and up to 20000 stocks in a few seconds, depending on the random values generated.

One thing that I ran into was that clicking the RUN button while running something else in Eclipse did _not_ terminate the previous thing running. I'm used to IDEs that do that, so it's a force of habit. I had a couple loops that were slowing me down, so I was tweaking them and testing every little change, but not terminating the previous running programs. I didn't realize why my computer was overheating until I threw in a few print statements and saw the repeat values coming out of the loop and realized they were running concurrently. I've got to get in the habit of pressing the red button to terminate.

**Comment by WesleyTo** [comment]
@pricedjp 
For learning in general, I find that small videos are only good for quick learning because content-makers are so concerned with brevity that they generally become too afraid to delve deeply into the material. When it comes to programming and CompSci, the devil is in the details, and those details tend to get glossed over in a lot of short videos. I usually balance it 30% short videos, just for getting up to speed quickly and as a sanity-check when coding, then 70% book or long-form lectures for real-in-depth coverage.

**Comment by trungphung** [comment]
What struggles and major questions are you experiencing as you work your way through this section of the project? What errors, bugs and other pesky stuff are you encountering?
Hello,
I followed the videos and having no problem.  However, following doesn't mean understanding.  I still don't feel solid about what I learned.  When I followed the video, a lot of errors come from mistyping or syntax.
Trung Phung

**Comment by Sweeter-man** [comment]
Similar to my many of class mates i'm learning the code for a beginning level, so I am trying to familiarize myself with the tool set of programming (arrays, loops, variables and conditional statement). 
and  then how they are all connected to methods and classes. Its takes some time to fully grasp. 

I understand that with practice and repetition, I will feel more comfortable with the language and gain the complete tool set I need to build code. I look forward to the feeling of "liberation".

**Comment by stefanbund** [comment]
I understand what you're going through right now. The first part of the class introduces all the major building blocks of programs, so there is a lot of material. Soon, you will find that the skill set will begin to plateau, and you'll feel like you can throw any of those skills at a given problem.

From Stefan

**Comment by stefanbund** [comment]
This is a great comment, it is very true. Eclipse may execute several applications when you press the green button, so you should actually left click on your project yourself then run that very program. This will force your current application of the top of eclipses compilation stack, and omit the others.

Since I use eclipse professionally, I find that I have work applications that I put aside before I go to class and teach. This means that sometimes when I'm in class, my work stuff gets compiled for everyone.

From Stefan
